language: python 

before_install: 
  - pip install mkdocs 
  - pip install mkdocs-cinder 
  - pip install pymdown-extensions

script: ./scripts/docbuild.sh  
  - mkdocs build 
  - 

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
